### ISSUE TITLE
Error installing Python 3 Version of DomoPad 

### ISSUE THREAD

**Issue by ryanbuckner** [RogueProeliator/indigo-plugins-googleclients#8]
Installed on Indigo 2022.1br2

`   Domotics Pad Clients Error      Error in plugin execution InitializeMain:

type: ('multiple exception types must be parenthesized', ('plugin.py', 390, 10, '\t\texcept urllib2.HTTPError, e:\n', 390, 30))`

**Comment by RogueProeliator** [comment]
That branch is not ready for prime-time yet, though getting close on my local machine... having to unexpectedly fix some errors in some shared code.  I anticipate having a version pushed this week that will at least install (then to testing with your original issue...)
